/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSerialPort */

#ifndef _Included_com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSerialPort
#define _Included_com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSerialPort
 * Method:    openSerialPort
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSerialPort_openSerialPort
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSerialPort
 * Method:    searchAvailablePort
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSerialPort_searchAvailablePort
  (JNIEnv *, jclass);

/*
 * Class:     com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSerialPort
 * Method:    readSerialPort
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSerialPort_readSerialPort
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSerialPort
 * Method:    writeSerialPort
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSerialPort_writeSerialPort
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSerialPort
 * Method:    isConnected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSerialPort_isConnected
  (JNIEnv *, jclass);

/*
 * Class:     com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSerialPort
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSerialPort_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
