/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils */

#ifndef _Included_com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils
#define _Included_com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils
 * Method:    BoxWindow
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils_BoxWindow
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils
 * Method:    FileChooseWindow
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils_FileChooseWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils
 * Method:    DirectoryChooseWindow
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils_DirectoryChooseWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils
 * Method:    LongTest
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils_LongTest
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils
 * Method:    SetCursorPos
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils_SetCursorPos
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils
 * Method:    Click
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils_Click
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils
 * Method:    GetCursorPos
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils_GetCursorPos
  (JNIEnv *, jclass);

/*
 * Class:     com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils
 * Method:    SaveCapture
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils_SaveCapture
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils
 * Method:    GetLastError
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils_GetLastError
  (JNIEnv *, jclass);

/*
 * Class:     com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils
 * Method:    GetHWND
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_thzs_app_datacoplite_util_Native_windows_NativeWindowsSupportUtils_GetHWND
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
